# Check if code checked into external resources (blogs, tutorials)
# that we also track in our CI is affected by a PR.
# In that case, we add a label to the PR (`external-code-affected`) and
# add a comment to make sure that the external code still works and is
# eventually updated.
name: External code check

on: pull_request_target

jobs:
  check-changes:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
      
    - name: Check for changes in tracked files
      run: |
        set -xe
        git clone -b external-code https://github.com/ray-project/buildkite-ci-pipelines ./pipelines 

        # Find changed files
        GIT_DIFF=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
        
        echo "All changed files:"
        echo "$GIT_DIFF"
        
        GIT_DIFF_SERIALIZED=$(echo "$GIT_DIFF" | tr '\n' '|')
        echo "GIT_DIFF_SERIALIZED=$GIT_DIFF_SERIALIZED" >> $GITHUB_ENV

    - name: Add label and comment if a tracked file changed
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const {
            deserializeIntoArray,
            filterFilesByNames,
            getCommentContentChanged,
            getCommentContentNotChanged,
            parseTrackedFilesToURIs,
            readFileContent
          } = require('./pipelines/external_code_tracker/track_code');
          
          const fs = require("fs");
          
          const commentHeader = `## Attention: External code changed`
          const externalCodeFile = "external_code.txt" 
          
          // Get existing comments
          const existingComments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          
          // Find comment by the bot that starts with the header
          let commentToUpdate = existingComments.data.find(comment =>
            comment.user.login === 'github-actions[bot]' && comment.body.startsWith(commentHeader)
          );
          
          // Read and parse external_code.txt file
          let externCodeFileContent = fs.readFileSync(externalCodeFile, "utf8");
          let trackedFilesToURIs = parseTrackedFilesToURIs(externCodeFileContent);
          
          console.log("trackedFileToURIs")
          console.log(trackedFilesToURIs)
          
          // Get changed files from environment variable
          let changedFiles = await deserializeIntoArray(process.env.GIT_DIFF_SERIALIZED)
          
          console.log("changedFiles")
          console.log(changedFiles)
          
          // Filter associative array
          let changedFileToURIs = filterFilesByNames(trackedFilesToURIs, changedFiles);
          
          console.log("changedFileToURIs")
          console.log(changedFileToURIs)
          
          if (changedFileToURIs.length === 0) {
            if (commentToUpdate) {
                commentBody = getCommentContentNotChanged(commentHeader);
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: commentToUpdate.id,
                  body: commentBody
                });
            }
          
          } else {
              commentBody = getCommentContentChanged(commentHeader, changedFileToURIs);
          
              if (commentToUpdate) {
              // Only update if content changed
              if (commentBody !== commentToUpdate.body) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: commentToUpdate.id,
                  body: commentBody
                });
              }
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['external-code-affected']
            });
          
          }

